//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_Employee
    {
        public System.Guid EmID { get; set; }
        public string EMUserName { get; set; }
        public string EMPassWord { get; set; }
        public string EMRealName { get; set; }
        public string EmType { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    }
}
