//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_Tasks
    {
        public System.Guid TasksID { get; set; }
        public string TaskNeeds { get; set; }
        public Nullable<double> ExecutorScore { get; set; }
        public Nullable<double> TechnicalFactor { get; set; }
        public Nullable<double> TimeFactor { get; set; }
        public Nullable<double> DemandDetailFactor { get; set; }
        public Nullable<double> TestEvaluteFactor { get; set; }
        public Nullable<double> NeedsEvaluteFactor { get; set; }
        public Nullable<double> ExecutorGetScore { get; set; }
        public Nullable<System.Guid> Executor { get; set; }
        public Nullable<double> TestFactor { get; set; }
        public Nullable<double> OnlinePublishFactor { get; set; }
        public Nullable<double> TestScore { get; set; }
        public Nullable<System.Guid> TestEmployee { get; set; }
        public Nullable<double> DemandFactor { get; set; }
        public Nullable<double> DemandScore { get; set; }
        public Nullable<System.Guid> DemandEmployee { get; set; }
        public string FinishStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    }
}
